---
title: "Reproducible Research: Peer Assessment 1"
author: "CMI"
date: "29/12/2020"
output: html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#install pacman to check for required packages
if (!require('pacman')) install.packages('pacman'); library(pacman) 

# load (install if required) packages from CRAN
p_load("dplyr", "lattice", "lubridate", "tidyverse",  "data.table")




```



## Loading and preprocessing the data
```{r Loading and preprocessing the data}

#Directory is Reproducible Research
#Check if a data folder exists, and if not, Create one

if(!file.exists("data")){
        dir.create("data")
}


#unzip data folder from repo clone and save data in data folder
zipfile <- "./RepData_PeerAssessment1/activity.zip"
unzip(zipfile, exdir = "./data", unzip = "internal")
list.files("./data")

# Load .csv into R
activity <- read.csv("./data/activity.csv", header = TRUE)

#Check structure of data
str(activity)

#Covert date variable to date format
activity$date <- as.POSIXct(activity$date, format="%Y-%m-%d")

```



## What is mean total number of steps taken per day?
```{r Mean Steps Per Day}

activity_m <- activity %>% 
    group_by(date) %>% 
    summarize(step_day = mean(steps, na.rm=TRUE)
```




## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
